automation:
  enabled: true
  name: downstreams
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'extract-load'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-transform
      config:
        flow: transform-demo
