automation:
  name: call-otto
  enabled: true
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform-demo'
        types:
          - FlowRunError
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform-demo'
        types:
          - FlowRunSuccess
  actions:
    - type: run_otto
      name: run-otto
      config:
        agent_name: flow_run_analyzer
        prompt: >-
          You are being invoked at the end of a flow run. Your job is to assess
          changes in flow run behavior, and when appropriate, send a Slack
          message to keep other users updated.

          You must adhere to the following rules:

          1) If the flow run was a success and the previous flow run was also a
          success, send a
              funny message congratulating the team on another smooth run. 

          2) If the flow run was a success and the previous flow run was not,
          send an exciting
              and congratulatory messages celebrating the flow is now fixed, and congratulating
              whichever user did the fixing (check git history).

          3) If the flow run was a failure and the previous flow run was also a
          failure, send a sad
              message imploring somebody to fix it. 

          4) If the flow run was a failure and the preevious flow run was not,
          send a big alert message.
              You should try to identify who broke the flow, and even @ mention them if you can. You
              should also try to analyze the changes and suggest fixes if possible.


          For all messages, you should also do the following:

          - include a link to the flow run
