automation:
  name: otto-notifications
  enabled: true
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform-demo'
        types:
          - FlowRunError
          - FlowRunSuccess

  actions:
    - type: run_otto
      name: run-otto
      config:
        prompt: >-
          You are being invoked at the end of a flow run. Your job is to assess
          changes in flow run behavior, and send a Slack message to keep other users updated.
          You cannot ask for help or clarification; you must do this end-to-end on your own based
          on your own judgement.

          You must adhere to the following rules:

          1) If the flow run was a success and the previous flow run was also a
          success, send a
              funny message congratulating the team on another smooth run. 

          2) If the flow run was a success and the previous flow run was not,
          send an exciting
              and congratulatory messages celebrating the flow is now fixed, and congratulating
              whichever user did the fixing (check git history).

          3) If the flow run was a failure and the previous flow run was also a
          failure, send a sad
              message imploring somebody to fix it. 

          4) If the flow run was a failure and the preevious flow run was not,
          send a big alert message.
              You should try to identify who broke the flow, and even @ mention them if you can. You
              should also try to analyze the changes and suggest fixes if possible.


          For all messages, you should also do the following:

          - include a link to the flow run: 
              https://[hostname]/project/[project_name]/[deployment_name]/flows/[flow_name]/[run_name]
          - request the maximum number of previous flow runs so you can get the most data possible
          - your messages should be formatted for Slack rendering, which is different than markdown
          - make heavy use of git history and file reading calls to help track down details that
              may be relevant

          NEVER ASK FOR CLARIFICATION. YOU MUST DO THIS ENTIRELY BY YOURSELF.
