automation:
  enabled: true
  name: transform-demo
  triggers:
    events:
      - sql_filter: json_extract_string(event, '$.data.flow') = 'transform'
        types:
          - FlowRunSuccess
  actions:
    - type: run_flow
      name: run-metrics
      config:
        flow: metrics
    - type: run_flow
      name: run-llm
      config:
        flow: llm
